spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

security:
  username: user
  password: test
  oauth2:
    client:
      client-id: foo
      client-secret: bar
